/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package me.underlow.tgarr.models.radarr


/**
 *
 *
 * @param ignoreEpisodesWithFiles
 * @param ignoreEpisodesWithoutFiles
 * @param monitor
 * @param searchForMovie
 * @param addMethod
 */


data class AddMovieOptions (

    val ignoreEpisodesWithFiles: kotlin.Boolean = true,

    val ignoreEpisodesWithoutFiles: kotlin.Boolean = true,

    val monitor: MonitorTypes = MonitorTypes.movieOnly,

    val searchForMovie: kotlin.Boolean = false,

    val addMethod: AddMovieMethod = AddMovieMethod.manual

)

