/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package me.underlow.tgarr.models.radarr

import com.fasterxml.jackson.annotation.JsonIgnoreProperties

@JsonIgnoreProperties(ignoreUnknown = true)
data class MovieResource(

    val id: kotlin.Int? = null,

    val title: kotlin.String? = null,

    val originalTitle: kotlin.String? = null,

    val secondaryYear: kotlin.Int? = null,

    val secondaryYearSourceId: kotlin.Int? = null,

    val sortTitle: kotlin.String? = null,

    val sizeOnDisk: kotlin.Long? = null,

    val status: MovieStatusType? = null,

    val overview: kotlin.String? = null,

    val website: kotlin.String? = null,

    val remotePoster: kotlin.String? = null,

    val year: kotlin.Int? = null,

    val hasFile: kotlin.Boolean? = null,

    val youTubeTrailerId: kotlin.String? = null,

    val studio: kotlin.String? = null,

    val path: kotlin.String? = null,

    val qualityProfileId: kotlin.Int? = null,

    val monitored: kotlin.Boolean? = null,

    val minimumAvailability: MovieStatusType? = null,

    val isAvailable: kotlin.Boolean? = null,

    val folderName: kotlin.String? = null,

    val runtime: kotlin.Int? = null,

    val cleanTitle: kotlin.String? = null,

    val imdbId: kotlin.String? = null,

    val tmdbId: kotlin.Int? = null,

    val titleSlug: kotlin.String? = null,

    val rootFolderPath: kotlin.String? = null,

    val folder: kotlin.String? = null,

    val certification: kotlin.String? = null,

    val genres: kotlin.collections.List<kotlin.String>? = null,

    val tags: kotlin.collections.Set<kotlin.Int>? = null,

//    val added: java.time.OffsetDateTime? = null,

    val addOptions: AddMovieOptions? = null,

//    val ratings: Ratings? = null,

//    val movieFile: MovieFileResource? = null,
//
//    val collection: MovieCollection? = null,

//    val popularity: kotlin.Float? = null

)

