/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package me.underlow.tgarr.models.radarr



/**
 *
 *
 * Values: tmdb,mappings,user,indexer
 */

enum class SourceType(val value: kotlin.String) {

    tmdb("tmdb"),

    mappings("mappings"),

    user("user"),

    indexer("indexer");

    /**
     * Override toString() to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is SourceType) "$data" else null

        /**
         * Returns a valid [SourceType] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): SourceType? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

