/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package me.underlow.tgarr.models.sonarr


data class AddSeriesOptions(

    val ignoreEpisodesWithFiles: kotlin.Boolean = true,

    val ignoreEpisodesWithoutFiles: kotlin.Boolean = true,

    val monitor: MonitorTypes = MonitorTypes.all,

    val searchForMissingEpisodes: kotlin.Boolean = false,

    val searchForCutoffUnmetEpisodes: kotlin.Boolean = false

)

