/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package me.underlow.tgarr.models.sonarr

import com.fasterxml.jackson.annotation.JsonIgnoreProperties

@JsonIgnoreProperties(ignoreUnknown = true)
data class SeriesResource (

    var id: kotlin.Int? = null,

    val title: kotlin.String? = null,

    val sortTitle: kotlin.String? = null,

//    val status: SeriesStatusType? = null,

    val ended: kotlin.Boolean? = null,

    val profileName: kotlin.String? = null,

    val overview: kotlin.String? = null,

    val network: kotlin.String? = null,

    val airTime: kotlin.String? = null,

//    val images: kotlin.collections.List<MediaCover>? = null,

    val remotePoster: kotlin.String? = null,

//    val seasons: kotlin.collections.List<SeasonResource>? = null,

    val year: kotlin.Int? = null,

    val path: kotlin.String? = null,

    var qualityProfileId: kotlin.Int? = null,

    val seasonFolder: kotlin.Boolean? = null,

    var monitored: kotlin.Boolean? = null,

    val useSceneNumbering: kotlin.Boolean? = null,

    val runtime: kotlin.Int? = null,

    val tvdbId: kotlin.Int? = null,

    val tvRageId: kotlin.Int? = null,

    val tvMazeId: kotlin.Int? = null,


//    val seriesType: SeriesTypes? = null,

    val cleanTitle: kotlin.String? = null,

    val imdbId: kotlin.String? = null,

    val titleSlug: kotlin.String? = null,

    var rootFolderPath: kotlin.String? = null,

    val folder: kotlin.String? = null,

    val certification: kotlin.String? = null,

    val genres: kotlin.collections.List<kotlin.String>? = null,

    val tags: kotlin.collections.Set<kotlin.Int>? = null,


    var addOptions: AddSeriesOptions? = null,

//    val ratings: Ratings? = null,

//    val statistics: SeriesStatisticsResource? = null,

    val episodesChanged: kotlin.Boolean? = null,

    @Deprecated(message = "This property is deprecated.")
    var languageProfileId: kotlin.Int? = null

)

